# Generated by Django 4.2.28 on 2026-02-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expertise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(unique=True)),
                ("icon", models.CharField(max_length=50)),
                ("summary", models.TextField()),
                ("description", models.TextField()),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="expertises/"),
                ),
                ("legal_elements", models.JSONField(default=list)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
