# Generated by Django 4.2.28 on 2026-02-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("expertises", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="team/")),
                ("biography", models.TextField()),
                ("skills", models.JSONField(default=list)),
                ("facebook", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("whatsapp", models.CharField(blank=True, max_length=20)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "expertises",
                    models.ManyToManyField(
                        blank=True, related_name="lawyers", to="expertises.expertise"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
